### PR TITLE
Improve breakpoint for stacking summary question above answer and action

### LINKED ISSUE #198: Improve summary stacking breakpoint
The breakpoint for changing from layout to have question, answer, and action all on one row, vs question above answer and action is currently set to > 25 chars for the answer length. This could probably be bumped up to 50 chars.

_Originally posted by @bameyrick in https://github.com/ONSdigital/pattern-library-v2/issues/84#issuecomment-465139074_

### PR DESCRIPTION
**Pull request by bameyrick**
Will resolve #198

### CODE REVIEW

**Comment by bameyrick** [comment]
[Improve summary stacking breakpoint](https://trello.com/c/hWkFGVWe/161-improve-summary-stacking-breakpoint)

**Comment by boxadesign** [comment]
Is there anywhere I can view this pattern?

**Comment by boxadesign** [comment]
Spotted some padding that's not wanted:

image

**Comment by bameyrick** [comment]
Should have fixed those spacing issues now.

**Pull request merged**
